### ISSUE TITLE
Fix links detection RegEx

### ISSUE THREAD

**Issue by p-himik** [tsoding/HyperNerd#197]
1. Domains can be 1 character
2. Domains can be more than 256 characters, especially when there's also username and password
3. TLD could also be 1 character in the future
4. TLD could be more than 6 characters (look at https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains)
Probably there're other problems.

Probably, the best approach would be to just try to parse it with some library. E.g. https://hackage.haskell.org/package/uri-bytestring

**Comment by rexim** [comment]
@p-himik uri-bytesting not only fails to parse URLs without the scheme, but also fails all of your mentioned above cases. Nice try! Thanks for the test cases though. :)
