### ISSUE TITLE
Documentation about ini files is outdated

### ISSUE THREAD

**Issue by rexim** [tsoding/HyperNerd#484]
introduced in #482
  - Several bot configurations per file
  - Sections with `bot:` prefix

**Comment by jspaulsen** [comment]
This is biting me currently :sob:

**Comment by rexim** [comment]
@jspaulsen is it better now? de0f2a26d8ac938b693f6bbff95b3290b0682474

**Comment by jspaulsen** [comment]
Much, thank you!
