### ISSUE TITLE
Documentation for bot configuration is misnomer and needs more detail

### ISSUE THREAD

**Issue by jspaulsen** [tsoding/HyperNerd#576]
For twitch credentials,
`password` is a misnomer; it's technically an  `oauth` token; a corollary of this is the documentation should detail if the `oauth:` prefix is necessary (it is, but :man_shrugging: )

**Comment by rexim** [comment]
@jspaulsen is it better now? d8f664c2f24ea52508fc1decb5afc507b30662ea

**Comment by jspaulsen** [comment]
I'd argue for using `oauth` instead of `password` as the config key but otherwise, yes.

**Comment by rexim** [comment]
@jspaulsen I agree. But that requires also changing the code, so it sounds kinda outside of the scope of just changing the documentation. Created a separate issue for that #579
