### ISSUE TITLE
!demo

### ISSUE THREAD

**Issue by JAremko** [tsoding/HyperNerd#622]
Kinda need a !demo command for testing complex commands/chains of commands.  Basically when you do `!demo !ban tsoding` the output will go to your private messages instead of stream chat. Alternatively the bot should also process private messages - when you pm it  `!ban tsoding` it will respond to you (via private chat) with `tsoding has been banned`

**Comment by rexim** [comment]
@JAremko try `!ban tsoding | !wme`

**Comment by JAremko** [comment]
!ban tsoding | !wme

**Comment by JAremko** [comment]
:thinking:

**Comment by JAremko** [comment]
`MrBotka: You asked me to whisper you this: "tsoding has been banned"`

Kinda close. But Answering to PM would be even better.

**Comment by rexim** [comment]
@JAremko If you just need the bot to be able to respond in PM why even have that weird !demo command?

**Comment by JAremko** [comment]
@JAremko those are two ways to implement the same thingy. !wme is lik !demo. But PMing would be even better. :thinking:

**Comment by rexim** [comment]
@JAremko got it. Created #625 for that.
