### ISSUE TITLE
Consider using CircleCI for testing.

### ISSUE THREAD

**Issue by JAremko** [tsoding/HyperNerd#623]
CircleCI  has free for open source plan(with X4 parallelism last time I checked) so you can run [4 tests concurrently](https://circleci.com/docs/2.0/parallelism-faster-jobs/), it can [cache dependencies](https://circleci.com/docs/2.0/caching/) and it has [first class Docker integration](https://circleci.com/blog/docker-what-you-should-know/).

Here's [Haskell Stack example](https://circleci.com/docs/2.0/language-haskell/)

**Comment by rexim** [comment]
I have considered! Thanks!
