### ISSUE TITLE
There is no command that shows info about next stream so i have to open the !schedule page and thats annoying

### ISSUE THREAD

**Issue by Nufflee** [tsoding/HyperNerd#670]

**Comment by rexim** [comment]
I think it's just the matter of parsing https://tsoding.github.io/schedule/schedule.json on the bot side

**Comment by rexim** [comment]
@Nufflee implemented in and deployed dba90078a10ad8fcaacaff094751e6f99bf77200 There is now a `!nextstream` command. Please close the issue if the solution works for you.
