### ISSUE TITLE
make the bot randomly refuse to execute commands and just says "no"

### ISSUE THREAD

**Issue by Nufflee** [tsoding/HyperNerd#691]

**Comment by rexim** [comment]
Sounds interesting, but only if we do that for plebs with absolutely no roles.

**Comment by rexim** [comment]
After a second thought, I don't really like this idea. We want to be more welcoming to new people not the other way around. Because we are a friendly PHP community. ![](https://static-cdn.jtvnw.net/emoticons/v1/1699746/1.0)
