### ISSUE TITLE
Default argument feature for custom command

### ISSUE THREAD

**Issue by SuperCuber** [tsoding/HyperNerd#779]

**Comment by rexim** [comment]
@SuperCuber could you please be more specific? How exactly do you see that feature working?

**Comment by SuperCuber** [comment]
Maybe like `!funny` does `Tsoding made funny joke 0 times` but `!funny SuperCuber` is `SuperCuber made funny joke 0 times`, not sure what the syntax for `!addcmd` should be.


This and the issue that allows `%times(other_command)` might need to redesign https://github.com/tsoding/HyperNerd/blob/985bc39bffea9a470ec2ba3fe9a2ee3c11e0fa8b/src/Bot/CustomCommand.hs#L181

**Comment by rexim** [comment]
Blocked by #599
