### ISSUE TITLE
!asciify doesn't work in irc backend

### ISSUE THREAD

**Issue by Glog78** [tsoding/HyperNerd#789]
I use an irc client usally to connect to twitch. So i noticed when doing so the line wrap doesn't work. Feel free to close if  the effort isn't worth the time because of the low usage of irc clients to twitch nowadays.

additional data:
irc client -> weechat

preview of the issue:
![grafik](https://user-images.githubusercontent.com/7598856/65392329-fb621f00-dd73-11e9-8d38-05b886a691a8.png)

**Comment by rexim** [comment]
@Glog78 yep, you got it right! I also use a thirdparty client and this is exactly how it looks like for me unless I resize my window. The command is designed to work for the web version of Twitch chat which is what majority of the people use.
