### ISSUE TITLE
Link restriction for non-subscribers can be bypassed by not including http:// or https://

### ISSUE THREAD

**Issue by The-Renaissance** [tsoding/HyperNerd#790]
![issue image](https://user-images.githubusercontent.com/25717879/65399013-661d5580-dd88-11e9-9a16-ecb5d8340a03.png)
![issue image 2](https://user-images.githubusercontent.com/25717879/65399065-ab418780-dd88-11e9-9a93-65f281b75574.png)
![issue image 3](https://user-images.githubusercontent.com/25717879/65399092-c44a3880-dd88-11e9-8643-95df5af26781.png)

**Comment by The-Renaissance** [comment]
These images were taken from the stream on Sep 22, 2019.

**Comment by rexim** [comment]
Links are not allowed to non-trusted users. Subscription is only one way to gain the trust. Mods can explicitly trust people manually. This user is trusted manually.
