### ISSUE TITLE
youtube link regex is broken

### ISSUE THREAD

**Issue by PaprikaX33** [tsoding/HyperNerd#791]
The youtube link finder regex on `!friday` command is broken when the first character of the video id is `-`

**Comment by rexim** [comment]
@PaprikaX33 duplicate of #715 sorry

**Comment by PaprikaX33** [comment]
Whoops, sorry. I missed it when searching for possible duplicates

**Comment by rexim** [comment]
@PaprikaX33 don't worry, the wording is completely different. No surprise it was hard to find. :smiley:
